# python dockerfile for backend

#Uses node 22 as base
FROM node:22

#Goes to the app directory
WORKDIR /app

COPY package*.json ./

#Install dependencies
RUN npm install

#Copy the application files
COPY . .

#Set port environment variable
ENV PORT=9669

#Expose the port
EXPOSE 9669

CMD ["npm", "start"]

