# Generated by Django 5.2.6 on 2025-10-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_userprofile_starting_balance_userholdings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('previous_close', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('market_state', models.CharField(blank=True, max_length=20, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('date_founded', models.DateTimeField(blank=True, null=True)),
                ('zodiac_sign', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['ticker'],
            },
        ),
    ]
