# Generated by Django 5.2.6 on 2025-10-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZodiacSignMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_sign', models.CharField(max_length=50)),
                ('stock_sign', models.CharField(max_length=50)),
                ('match_type', models.CharField(choices=[('positive', 'Positive Match'), ('neutral', 'Neutral Match'), ('negative', 'Negative Match')], max_length=20)),
                ('element', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Zodiac Sign Matching',
                'verbose_name_plural': 'Zodiac Sign Matchings',
                'ordering': ['user_sign', 'match_type'],
                'unique_together': {('user_sign', 'stock_sign')},
            },
        ),
    ]
