# Generated by Django 5.2.6 on 2025-10-11 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_zodiacsignmatching'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStockPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('preference_type', models.CharField(choices=[('watchlist', 'Watchlist'), ('dislike', 'Dislike')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Stock Preference',
                'verbose_name_plural': 'User Stock Preferences',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'ticker')},
            },
        ),
    ]
