# Generated by Django 5.2.6 on 2025-10-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0007_stockholding_purchase_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHoroscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zodiac_sign', models.CharField(choices=[('Aries', 'Aries'), ('Taurus', 'Taurus'), ('Gemini', 'Gemini'), ('Cancer', 'Cancer'), ('Leo', 'Leo'), ('Virgo', 'Virgo'), ('Libra', 'Libra'), ('Scorpio', 'Scorpio'), ('Sagittarius', 'Sagittarius'), ('Capricorn', 'Capricorn'), ('Aquarius', 'Aquarius'), ('Pisces', 'Pisces')], max_length=50)),
                ('investing_style', models.CharField(choices=[('casual', 'Casual Explorer'), ('balanced', 'Balanced Seeker'), ('profit-seeking', 'Profit Seeker'), ('playful', 'Playful Mystic')], max_length=50)),
                ('date', models.DateField(db_index=True)),
                ('horoscope_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Horoscope',
                'verbose_name_plural': 'Daily Horoscopes',
                'ordering': ['-date', 'zodiac_sign'],
                'unique_together': {('zodiac_sign', 'investing_style', 'date')},
            },
        ),
    ]
